### ISSUE TITLE
Convert RFC/I-D references into the auto-fetch format

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rfc-asciidoc-rfc#10]
As title.

**Comment by opoudjis** [comment]
I'm doing this, by which I assume leave only titles and the anchors in the existing RFC reference files; the fetching of entities of course ignores everything but the anchor anyway.

**Comment by ronaldtse** [comment]
Could you also help remove the actual reference files so asciidoctor-bibliography could generate the bibliography automatically?

**Comment by opoudjis** [comment]
To confirm: you want not to have include files, but preprocess this through Asciidoc-bibliography, with a single references file, which will include the skeleton references for RFC documents?

**Comment by ronaldtse** [comment]
The best way would be to modify the bibliography gem to take a directory of xml files, and the ones that are RFC/IDs could come from the cache? What do you think?

**Comment by opoudjis** [comment]
.... Instead of the current approach of a single bibliography file? I'd prefer the single file, it's neater, and you don't have to specify the alternative of a single file or a directory. The current structure of two different directories would not work either: the entire point of the biblio gem is that it picks whether a reference is informative or normative.

**Comment by ronaldtse** [comment]
Yes. That’s what I thought before to have a single file, but as you can see in documents with lots of references like this one: https://github.com/riboseinc/rfc-crypto-sm4 it becomes completely unmanageable because of the sheer number of references. 

It works much better when the reference files are separately included.

**Comment by ronaldtse** [comment]
I think the bibliography gem should hook into the <<>> syntax so that informative references could just be cited like that. Normative ones could use the “cite:” syntax ?

**Comment by opoudjis** [comment]
I'm scared to touch Paolo's code, but I take it Paolo is no longer available? Sure, but I'll need to work out how these macros work, and whether I can put business logic in them. I suspect that overloading <<>> won't work, but coming up with something more succinct than cite::norm and cite::info should be possible (just norm[] and info[], in fact).

**Comment by opoudjis** [comment]
Abandoned, working with metanorma now
