### ISSUE TITLE
Spanx elements should not be inserted into section titles (v2)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rfc-asciidoc-rfc#12]
This line:
```
=== Preprocessing Using `asciidoctor-bibliography`
```

Produces:
```
17.2.  Preprocessing Using <spanx style="verb">asciidoctor-
       bibliography</spanx>
```

Through `xml2rfc`.

Therefore section titles should not accept `<spanx>` elements. RFC 7749 doesn't quite specify what should be in the `<section>` `title` attribute, but presumably not XML elements. https://tools.ietf.org/html/rfc7749#section-2.34

In v3 RFC 7991, it does specify that then `<section>`'s `<name>` element can contain XML. https://tools.ietf.org/html/rfc7991#section-2.32

**Comment by opoudjis** [comment]
This follows from the fact that titles are attributes in v2, and attributes are not expected to contain formatting.

If IETF were already accepting RFC XML v3 as submissions, this would not be an issue...

**Comment by ronaldtse** [comment]
@opoudjis but in the V2 converter could we strip out the spanx elements from titles? We should not be generating incompatible output. Thanks!

**Comment by opoudjis** [comment]
This would have to be an option in the v3 converter, whereby v3 output is constrained to be backward compatible with v2. I'd rather make this just specific to this conversion, and script it in the Makefile.

**Comment by ronaldtse** [comment]
@opoudjis I don’t think we should implement in v3 but just in the v2. Can’t we separate title processing for v3 and v2 converters?

**Comment by opoudjis** [comment]
it's an issue in v2, and we will strip spanx from v2 output

**Comment by opoudjis** [comment]
Fixed in asciidoctor-rfc
