### ISSUE TITLE
Use better example RFCs

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rfc-asciidoc-rfc#13]
As mentioned by Adrian Farrell we should use better examples.

Now we have three examples in the `/examples` directory that are git submodules (each of them has its own repo).

@opoudjis (after the holidays) could you help:

1. Make the content here "original" (https://github.com/riboseinc/rfc-camelot-holy-grenade) so that we can use it in the document?
2. Think of a good, short example that can serve as the most "basic" example, and can be submoduled under the `/examples` directory.

**Comment by opoudjis** [comment]
I have completed revised Camelot RFC. Will not update template RFC for now.
