### ISSUE TITLE
Emphasize the benefit of using AsciiDoc over Markdown

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rfc-asciidoc-rfc#15]
From @opoudjis 
> emphasise the Unique selling point of asciidoc more, not much more work in data entry, but formal validation for free

**Comment by opoudjis** [comment]
In addition:

* clarify the terminology of AsciiDoc, Ascii RFC, and asciidoctor at the start.
* to add a justification to the effort: value adds include more extensive validation (incl workgroups), dynamic biblio, full coverage of RFC XML
* some final issues with warnings -- I think the 'example rfcs' are exceeding line width.
* final readthrough for consistency

**Comment by opoudjis** [comment]
> clarify the terminology of AsciiDoc, Ascii RFC, and asciidoctor at the start.

Already done.

**Comment by opoudjis** [comment]
Done. The Hebrew lines that are being reported as too long (because XML2RFC can't deal with Unicode), I can do nothing about. You also have a couple of too-long lines in the divination RFC,
