### ISSUE TITLE
Folding script problem: latest '07' version contains many "lines too long"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rfc-asciidoc-rfc#17]
This seems like a folding script problem.

In `examples/rfc-asciirfc-minimal/xml2/draft-asciirfc-minimal.xml` (the "folded" version), it contains these lines which are not correctly folded:

```xml
<section anchor="conventions" title="Terms and Definitions"><t>The key words "<spanx style="strong">MUST</spanx>", "<spanx style="strong">MUST NOT</spanx>", "<spanx style="strong">REQUIRED</spanx>", "<spanx style="strong">SHALL</spanx>",
```

```xml
  <section anchor="_example_1" title="Example 1"><t>Here&#8217;s an example of a properly wrapped code snippet in
accordance with rules specified in <xref target="code-snippets"/>.</t>
```

In fact, the lines are hardly folded.

**Comment by ronaldtse** [comment]
Tips from Adrian:

> Yes, the 72 character problem exists for all examples of code. That is,
things that would normally be allowed to continue wider that 72 characters
without a line break have to be represented in 72 characters with an
artificial line break.

> We're currently looking at a solution for YANG
(https://datatracker.ietf.org/doc/draft-wu-netmod-yang-xml-doc-conventions/).
Not that that helps you, but it lets you know that the problem is not
unique. What is done in these cases is to define (and explain) a
documentation convention to handle the line breaks.

>> 1. XML elements that are shown in code blocks, like this:
>> `"<!ENTITY I-D.ribose-asciirfc SYSTEM "https://xml2rfc.tools.ietf.org/public/rfc/bibxml3//reference.I-D.draft-ribose-asciirfc-04.xml">"`

> I think a URL may safely be split anywhere, but it is usually done at a
forward slash. So you would end up with something like...

> `<!ENTITY I-D.ribose-asciirfc SYSTEM
  https://xml2rfc.tools.ietf.org/public/rfc/
  bibxml3//reference.I-D.draft-ribose-asciirfc-04.xml">`

>> 2. We've inserted a line of Hebrew to demonstrate UTF-8 but xml2rfc is
rendering it like this:

>> ".&#1499;&#1488;&#1503; &#1488;&#1493;&#1500;&#1497;
&#1497;&#1502;&#1510;&#1488;&#1493;
&#1492;&#1502;&#1497;&#1500;&#1497;&#1501;â?â?¦

> Yeah, and I think the next revision of xml2rfc will do the same thing.
The question, I suppose is, does the line break matter in the example?
If it does, is it possible to come up with an even shorter snippet of Hebrew?

> The final escape on this would be to use a non-ASCII attachment (e.g.,
SVG) to include the snippet. That can be done (as it can be done for
figures), but it is a really ugly solution.

> If push comes to shove, post a revision with lines that are too long, and
we'll discuss the problem with the RFC Production Team.

**Comment by opoudjis** [comment]
Recall that the folding script is *NOT* folding every line in the file. It is only folding the lines inside CODE BEGINS... CODE ENDS examples, and ascii art/source code (tagged as CDATA). Those are the only lines xml2rfc has trouble with; it already folds the rest itself. The fact that examples/rfc-asciirfc-minimal/xml2/draft-asciirfc-minimal.xml is mostly unfolded is irrelevant, since that's not the submission; the lines from that file cited in the ascii RFC are.

**Comment by ronaldtse** [comment]
Yes, but the minimal xml file is already the “folded one”.  I thought it would be easier to debug.

**Comment by opoudjis** [comment]
Done.

**Comment by ronaldtse** [comment]
But we still have these occurrences?

```xml
<rfc xmlns:xi="http://www.w3.org/2001/XInclude" ipr="trust200902" updates="8140" sortRefs="true" tocInclude="true" submissionType="independent" prepTime="2018-04-13T09:23:42Z" version="3">
```

```xml
  <seriesInfo name="Internet-Draft" status="informational" stream="independent" value="draft-camelot-holy-grenade-00"/>
```

**Comment by opoudjis** [comment]
I think we're disagreeing on what needs to be done here. I understand that the point is not to get the RFC XML down to 72 characters per line, but the TXT output of xml2rfc; that means that the only XML that needs to be wrapped is the XML cited in code examples. The foregoing instances do in fact wrap in the TXT output:

````
  <CODE BEGINS>
  <rfc xmlns:xi= "http://www.w3.org/2001/XInclude" ipr= "trust200902"
  updates="8140" sortRefs="true" tocInclude="true"
  submissionType="independent" prepTime="2018-04-13T09:19:59Z"
  version="3">
````

````
  <seriesInfo name= "Internet-Draft" status= "informational"
  stream="independent" value="draft-camelot-holy-grenade-00"/>
````

If the wrapping requirement is on TXT and not the source XML, then we're ok.

**Comment by ronaldtse** [comment]
The only thing that needs to happen is `xml2rfc`'s TXT output is wrapped. That's all that matters in the submission at this stage 😉 

A lesser priority is to wrap Ascii Art nicely across page breaks 😆

**Comment by ronaldtse** [comment]
This is the TXT file generated at the root, lines like (these are within blocks of CODE BEGINS) these still overflow in TXT:
```
<spanx style="verb">&lt;CODE ENDS&gt;</spanx> blocks, as required by the IETF Trust Legal
Provisions (TLP) <xref target="IETF.TLP"/> specified in <xref target="RFC5378"/>.</t>
</section></section>
<section anchor="security" title="Security Considerations"><t>Any security considerations should be placed here.</t>
```

[draft-ribose-asciirfc-07.txt](https://github.com/riboseinc/rfc-asciidoc-rfc/files/1910213/draft-ribose-asciirfc-07.txt)
[draft-ribose-asciirfc-07.nits.txt](https://github.com/riboseinc/rfc-asciidoc-rfc/files/1910214/draft-ribose-asciirfc-07.nits.txt)

**Comment by opoudjis** [comment]
I was working from different version of RFC Minimal. The CODE BEGINS that the fold script is looking for needs to be at the beginning of the line.
