### ISSUE TITLE
Last edit

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/rfc-asciidoc-rfc#19]
From Lynne:
Sigh.... Just want to make sure that we should update Figure 15, after spotting the following in Figure 14:

:no-rfc-bold-bcp14: false

Does this text in Section 4.4 indicate that Figure 15 is actually OK as is? Apologies for also missing this before!

:no-rfc-bold-bcp14: false
overrides the wrapping by default of boldface uppercase BCP14
[RFC2119] words (e.g. "MUST NOT") with the "bcp14" element.

Thank you again!

**Comment by ronaldtse** [comment]
For the record, answer to the question was affirmative. Thanks!
