### ISSUE TITLE
Distinguish AsciiDoc syntax vs asciidoctor syntax

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rfc-asciidoc-rfc#3]
The original AsciiDoc syntax was defined here: http://www.methods.co.nz/asciidoc/

asciidoctor supports a superset of AsciiDoc - and lacks support in some parts. So they are slightly different.

We should distinguish them in the document. Specifically, we are using a superset of asciidoctor syntax.

**Comment by opoudjis** [comment]
Done.
