### ISSUE TITLE
Automatic citations of RFC and I-Ds

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rfc-asciidoc-rfc#5]
We should implement the functionality so that RFCs and I-Ds are automatically fetched. Managing them manually is quite a pain.

**Comment by opoudjis** [comment]
Do the changes to make all RFCs and IDs included, with minimal citation in any database file or reference source, satisfy this requirement?

**Comment by ronaldtse** [comment]
Yes I think so. Closing this.
